name: Tests
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
        # Optional: You can define inputs here that the user can provide
        # when triggering manually via the UI.
        # inputs:
        #   environment:
        #     description: 'Environment to deploy to'
        #     required: true
        #     default: 'staging'
        #   build_only:
        #     description: 'Skip deployment steps?'
        #     required: false
        #     type: boolean
        #     default: false  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-14/${{ hashFiles('**/package-lock.lock') }}
          restore-keys: v1/${{ runner.os }}/node-14/
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
